### ISSUE TITLE
[High] Cannot create columns or rows

### ISSUE THREAD

**Issue by awalias** [supabase/grid#56]
Cannot create new rows or columns where the default/first value in the dropdowns is used

![image](https://user-images.githubusercontent.com/458736/122904890-54b11500-d383-11eb-968b-d0b4107a26c4.png)
![image](https://user-images.githubusercontent.com/458736/122904923-5b3f8c80-d383-11eb-8914-7d523163be40.png)

If I select another option (either built in type or other custom type) it works

**Comment by phamhieu** [comment]
The problem is on SelectInput component. It doesn't have an empty value option. So it will show the first option on the list but the value is an empty string.

Fixed
<img width="659" alt="Screenshot 2021-06-24 at 6 26 18 AM" src="https://user-images.githubusercontent.com/689843/123180275-2a5f7480-d4b5-11eb-9edd-1839e526e0ad.png">

**Comment by phamhieu** [comment]
related supabase/infrastructure/issues/1231
